name: Publish My Resume

on:
  push:
      branches: [ main ]

  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9
        with:
          entrypoint: /bin/sh
          args: >-
            -c "
              tlmgr install ipaex luatexja &&
              tlmgr update latex &&
              pandoc --standalone --pdf-engine=lualatex -V documentclass=ltjsarticle --output=resume.pdf README.md # TODO: multi files support
            "
      - uses: actions/upload-artifact@master
        with:
          name: publish-my-resume
          path: resume.pdf
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          add: '.'
          message: 'publish pdf (auto)'
          push: true
