name: Publish My Resume

on:
  push:
      branches: [ main ]

  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: Convert Markdown to PDF
        run: |
          npm -g install markdown-pdf
          markdown-pdf -o resume.pdf README.md
      - uses: actions/upload-artifact@master
        with:
          name: publish-my-resume
          path: resume.pdf
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          add: '.'
          message: 'publish pdf (auto)'
          push: true
